---
title: "nimble_playground"
format:
  html:
    toc: true
    df-print: kable
execute:
  messages: false
  warnings: false
---

## Setup environment

```{r}
#| output: false
library(tidyverse)
library(nimble)
library(posterior)
library(bayesplot)

set.seed(123)

theme_set(theme_minimal())
```

## Read data

```{r}
data(sleepstudy, package = 'lme4')

head(sleepstudy)
```

## Specify joint model (likelihood + priors)

```{r}
sleepCode <- nimbleCode({
  for (i in 1:N) {
    Reaction[i] ~ dnorm(mu[i], sd = sigma_y)
    mu[i] <- (b0.f + b0.r[Subject[i]]) + (b1.f + b1.r[Subject[i]]) * Days[i]
  }
  
  # Priors for fixed effects (Population Level)
  b0.f ~ dnorm(0, sd = 100)
  b1.f ~ dnorm(0, sd = 100)
  
  # Priors for random effects (Subject Level)
  for (j in 1:J) {
    b0.r[j] ~ dnorm(0, sd = sigma_b0)
    b1.r[j] ~ dnorm(0, sd = sigma_b1)
  }
  
  # Priors for standard deviations (variance components)
  sigma_b0 ~ T(dnorm(0, sd = 100), 0, ) # Half-normal
  sigma_b1 ~ T(dnorm(0, sd = 100), 0, )
  sigma_y ~ T(dnorm(0, sd = 100), 0, )
})
```

## Condition on data and sample from posterior

```{r}
sleepData <- list(Reaction = sleepstudy$Reaction)

sleepConstants <- list(
  N = length(sleepstudy$Subject),
  J = length(unique(sleepstudy$Subject)),
  Days = sleepstudy$Days,
  Subject = as.numeric(factor(sleepstudy$Subject))
)

samples <- nimbleMCMC(
  code = sleepCode, 
  constants = sleepConstants, 
  data = sleepData,
  monitors = c("b0.f", "b1.f", "b0.r", "b1.r", "sigma_y", "sigma_b0", "sigma_b1"),
  niter = 4000, nburnin = 1000, nchains = 4,
  progressBar = FALSE
)

samples <- as_draws(samples)

summary(samples)
```

```{r}
pars <- c("b0.f", "b1.f", "sigma_b0", "sigma_b1", "sigma_y")

mcmc_combo(samples, pars = pars)
```
