---
title: "nimble_playground"
format:
  html:
    toc: true
    df-print: kable
execute:
  messages: false
  warnings: false
---

## Setup environment

```{r}
#| output: false
library(tidyverse)
library(nimble)
library(posterior)
library(bayesplot)

theme_set(theme_minimal())

set.seed(123)

M = 1000
```

## Simulate the Monty Hall problem

```{r}
play_monty_hall <- function() {
  # Car is randomly placed behind a door
  car_door <- sample(1:3, 1)
  
  # Contestant chooses a door
  contestant_door <- sample(1:3, 1)
  
  # Host opens a door (not the one with the car, not the one chosen by the contestant)
  possible_host_doors <- setdiff(1:3, c(car_door, contestant_door))
  
  if (length(possible_host_doors) > 1) {
      host_door <- sample(possible_host_doors, 1)
    } else {
      host_door <- possible_host_doors
    }
  
  remaining_door <- setdiff(1:3, c(contestant_door, host_door))
  
  # return true if switching door wins, false otherwise (i.e., keeping door wins)
  return(remaining_door == car_door)
}
```

```{r}
sim_dat <- map_lgl(1:M, ~ play_monty_hall())

prob_switch_wins <- mean(sim_dat)

prob_switch_wins
```



